<script setup>
import { ref, computed, onMounted } from 'vue';
import { classroomApi } from './classroomClient.js';
const students=ref([]), loading=ref(true), error=ref(''), query=ref(''), filter=ref('all'), detail=ref(null), detailBusy=ref(false), roster=ref(''), rosterBusy=ref(false), notice=ref('');
const storageNotice=ref(''), expiresAt=ref(null);
let requestId=0;
const filtered=computed(()=>students.value.filter(s=>(s.name+' '+s.studentId).includes(query.value.trim()) && (filter.value==='all' || filter.value==='none'&&!s.eventCount || filter.value==='started'&&s.eventCount>0&&s.completed<6 || filter.value==='done'&&s.completed===6)));
const started=computed(()=>students.value.filter(s=>s.eventCount>0).length), finished=computed(()=>students.value.filter(s=>s.completed===6).length);
const date=value=>value?new Date(value).toLocaleString('ko-KR'):'—';
const labels={activity:'활동 이동',reveal:'예상 확인',compare:'문맥 비교',sample:'확률 실험',generation:'토큰 생성',relationship:'개념 연결 실험',reflection:'서술 기록',answer:'이해 확인 응답',restart:'활동 다시 시작',advanced:'내부 원리 탐색'};
async function refresh(){loading.value=true;error.value='';try {const data=await classroomApi('/admin/students');students.value=data.students;storageNotice.value=data.storageNotice||'';expiresAt.value=data.expiresAt;}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function open(student){const id=++requestId;detailBusy.value=true;detail.value=null;error.value='';try{const data=await classroomApi('/admin/students/'+student.id);if(id===requestId)detail.value=data;}catch(e){if(id===requestId)error.value=e.message;}finally{if(id===requestId)detailBusy.value=false;}}
async function addRoster(){rosterBusy.value=true;error.value='';notice.value='';try{const lines=roster.value.trim().split(/\r?\n/).filter(Boolean);const entries=lines.map(line=>{const [studentId,...name]=line.split(/[\t,]/);return {studentId:studentId.trim(),name:name.join(' ').trim()};});const data=await classroomApi('/admin/roster',{students:entries});notice.value=`${data.added}명 등록했습니다. 이미 있는 동일 명단은 유지했습니다.`;roster.value='';await refresh();}catch(e){error.value=e.message;}finally{rosterBusy.value=false;}}
function eventText(event){const p=event.payload; if(event.kind==='answer'){const q=detail.value.answers.find(q=>q.id===p.questionId);return `${q?.title||p.questionId} · ${q?.options[p.choice]||p.choice} · ${p.correct?'정답':'오답'}`;}return Object.entries(p).map(([key,value])=>`${({stage:'활동',guess:'예상',reason:'이유 선택',context:'문맥',temperature:'온도',count:'횟수',token:'선택 토큰',action:'동작',experiment:'실험',text:'내용',page:'단계',hiddenDimension:'FFN 차원'})[key]||key}: ${typeof value==='object'?JSON.stringify(value):value}`).join(' · ');}
onMounted(refresh);
</script>
<template>
  <main class="admin-dashboard"><header class="admin-heading"><div><p class="classroom-kicker">INSTRUCTOR · LEARNING RECORDS</p><h1>학생 학습 기록</h1><p>첫 응답과 다시 고른 응답을 함께 확인하세요. 활동 기록은 학습 지원용이며, 화면을 열어 둔 시간만으로 출석을 판정하지 않습니다.</p></div><button class="classroom-secondary" :disabled="loading" @click="refresh">새로고침</button></header>
    <p v-if="storageNotice" class="classroom-notice">{{ storageNotice }} <strong v-if="expiresAt">만료 예정: {{ date(expiresAt) }}</strong></p>
    <p v-if="error" class="classroom-error" role="alert">{{ error }}</p><p v-if="notice" class="classroom-notice" role="status">{{ notice }}</p>
    <div class="admin-stats"><section><span>등록 학생</span><strong>{{ students.length }}<small>명</small></strong></section><section><span>활동 기록 있음</span><strong>{{ started }}<small>명</small></strong></section><section><span>6개 활동 완료</span><strong>{{ finished }}<small>명</small></strong></section><section><span>활동 기록 없음</span><strong>{{ students.length-started }}<small>명</small></strong></section></div>
    <p class="admin-note">학생은 이름·학번으로 바로 참여하며 처음 들어오면 명단에 자동 등록됩니다. 본인 확인 절차가 없는 간편 참여 방식이므로, 이 기록만으로 신원을 확인하거나 출석을 확정하지 마세요.</p>
    <details class="admin-roster"><summary>수강생 명단 미리 등록 · 선택 사항</summary><p>전체 명단을 미리 등록하면 아직 들어오지 않은 학생도 미참여로 확인할 수 있습니다. 명단 등록 없이도 학생이 이름·학번을 입력해 시작할 수 있습니다.</p><form @submit.prevent="addRoster"><label for="roster">한 줄에 학번,이름 · 엑셀 두 열을 복사해 붙여넣어도 됩니다.</label><textarea id="roster" v-model="roster" rows="5" placeholder="20260001,김학생" required maxlength="90000"></textarea><button class="classroom-primary" :disabled="rosterBusy">{{ rosterBusy?'등록 중…':'명단 등록' }}</button></form></details>
    <div class="admin-filters"><label>학생 검색<input v-model="query" type="search" placeholder="이름 또는 학번" /></label><label>참여 상태<select v-model="filter"><option value="all">전체 학생</option><option value="none">활동 기록 없음</option><option value="started">학습 중</option><option value="done">활동 완료</option></select></label><a class="classroom-secondary" href="/api/classroom/admin/export">전체 요약 CSV 내려받기</a><a class="classroom-secondary" href="/api/classroom/admin/export-details">응답·서술·활동 전체 내려받기</a></div>
    <p v-if="loading" role="status">학생 기록을 불러오는 중…</p><p v-else-if="!students.length" class="admin-empty">아직 등록된 학생이 없습니다. 학생이 이름·학번으로 들어오면 자동으로 표시됩니다. 미참여 학생까지 비교하려면 전체 명단을 미리 등록하세요.</p><p v-else-if="!filtered.length" class="admin-empty">조건에 맞는 학생이 없습니다.</p>
    <div v-else class="admin-table-wrap" tabindex="0" role="region" aria-label="학생 참여 현황표"><table><thead><tr><th>학번 · 이름</th><th>참여 상태</th><th>활동</th><th>문항 응답</th><th>첫 정답</th><th>최근 정답</th><th>최근 기록</th><th>상세</th></tr></thead><tbody><tr v-for="s in filtered" :key="s.id"><th><span>{{ s.studentId }}</span><strong>{{ s.name }}</strong></th><td>{{ s.completed===6?'활동 완료':s.eventCount?'학습 중':s.lastLogin?'로그인만 함':'미참여' }}</td><td>{{ s.completed }} / 6</td><td>{{ s.answered }} / 8</td><td>{{ s.firstCorrect }} / 8</td><td>{{ s.correct }} / 8</td><td>{{ date(s.updatedAt) }}</td><td><button class="classroom-secondary" @click="open(s)" :aria-label="`${s.name} 상세 기록 보기`">보기</button></td></tr></tbody></table></div>
    <p class="admin-note">활동 완료: 첫 예상 확인, 문맥·확률 활동의 이유 확인, 생성 종료, 3개 개념 실험의 이유 확인, 8문항 응답. 문항을 모두 맞혔는지는 정답 수로 따로 확인합니다.</p>
    <p v-if="detailBusy" role="status">상세 기록 불러오는 중…</p>
    <section v-if="detail" class="admin-detail" aria-label="학생 상세 기록"><header><div><p class="classroom-kicker">{{ detail.studentId }}</p><h2>{{ detail.name }}의 기록</h2><p>최근 로그인 {{ date(detail.lastLogin) }}</p></div><button class="classroom-secondary" @click="detail=null;requestId++">상세 닫기</button></header>
      <h3>활동별 진행</h3><ul class="admin-activity-list"><li v-for="a in detail.activities" :key="a.name"><span>{{ a.name }}</span><strong>{{ a.done?'완료':'진행 전 / 진행 중' }}</strong></li></ul>
      <h3>8문항 · 첫 응답과 최근 응답</h3><div class="admin-table-wrap" tabindex="0"><table><thead><tr><th>문항</th><th>첫 응답</th><th>최근 응답</th><th>응답 횟수</th></tr></thead><tbody><tr v-for="q in detail.answers" :key="q.id"><th>{{ q.title }}</th><td>{{ q.first ? q.options[q.first.choice] : '미응답' }}<b v-if="q.first" :class="q.first.correct?'answer-right':'answer-wrong'">{{ q.first.correct?'정답':'오답' }}</b></td><td>{{ q.latest ? q.options[q.latest.choice] : '미응답' }}<b v-if="q.latest" :class="q.latest.correct?'answer-right':'answer-wrong'">{{ q.latest.correct?'정답':'오답' }}</b></td><td>{{ q.attempts }}</td></tr></tbody></table></div>
      <h3>개념 연결 실험과 서술</h3><div class="admin-experiments"><section v-for="r in detail.relationships" :key="r.id"><h4>{{ r.title }} · {{ r.ran?'실행함':'미실행' }}</h4><p>예상: {{ r.guess || '미응답' }}</p><p>이유: {{ r.reason || '미응답' }} <b v-if="r.reason">({{ r.reasonCorrect?'정답':'다시 확인 필요' }})</b></p><blockquote>{{ r.reflection || '작성한 설명이 없습니다.' }}</blockquote></section></div><h3>최종 내 말로 설명하기</h3><blockquote class="admin-reflection">{{ detail.reflection || '작성한 설명이 없습니다.' }}</blockquote>
      <details class="admin-event-log"><summary>전체 활동 기록 {{ detail.events.length }}건 · 서버 수신 시각 순서</summary><ol><li v-for="event in detail.events" :key="event.id"><time>{{ date(event.at) }}</time><strong>{{ labels[event.kind] || event.kind }}</strong><p>{{ eventText(event) }}</p></li></ol></details>
    </section>
  </main>
</template>
